services:
  - type: web
    name: obl-digital-ftd-PGY-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dashboard_dep_ftd_app:server"
    plan: free
